-- ReflexiveReality — Master Import Manifest
--
-- Imports every library in the Reflexive Reality research program in dependency order.
-- After `lake build ReflexiveReality`, Lean has verified source files across 16 component
-- libraries (NEMS hub + sentience + phenomenology + transputation), zero sorry, and the
-- complete chain from closure axioms to physical laws to consciousness to ground.
import APS
import APSUndecidabilityInterfaces
import APSRecursionCompositionUniformity
import APSUniformization
import NemS
import Closure
import SelfReference
import Reflection
import SelectorStrength
import Sieve
import SemanticSelfDescription
import ArrowOfTime
import RefinementFlow
import RecordEntropy
import ErrorCorrectingClosure
import LawCalibration
import SemanticNonlocality
import CausalNonlocality
import FTLConstraints
import HolographyUnderClosure
import CertificationLogic
import Hypercomputation
import GPTClosure
import InstitutionalEpistemics
import EpistemicAgency
import InternalitySchema
import SurvivorCalculus
import AdmissibleContinuation
import ForcedAdjudication
import StructuralNonExhaustibility
import Transputation
import UgpLean
import ViableContinuation
import Sentience
import Phenomenology
import RepresentationalIncompleteness
import SemanticSelfReference
import SyntaxSemantics
import QualiaLedger
import ReflexiveClosure
import ReflexiveUnfolding
import NecessaryReflexiveIntelligence
import CalculusOfIntelligence
import RealityAsRecursiveIntelligence
import GhostCollapse
import LedgerGround
import Alpha
import GroundedExistence
import QualiaAlphaGrounded
import GroundManifestation
import AwarenessGround
import AlphaNonNull
import UnifiedPresence
import GoldenBridge
import ReflectiveFoldObstruction
import InfinityCompression
import Observer.Nonexhaustability
import ReflexiveArchitecture
import AdequacyArchitecture
import ReflexiveArchitectureNonexhaustibilityLean
import Philosophy
import FormalTheory
import Physics
import AIAgents
import ConsciousnessMind
